<?php
/**
 * LearnSubscriptionseatassociationBatchItems
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * LearnSubscriptionseatassociationBatchItems Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LearnSubscriptionseatassociationBatchItems implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'LearnSubscriptionseatassociationBatchItems';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'assignment_expiration' => 'string',
        'assignment_date' => 'string',
        'username' => 'string',
        'record_code' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'assignment_expiration' => 'assignment_expiration',
        'assignment_date' => 'assignment_date',
        'username' => 'username',
        'record_code' => 'record_code'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'assignment_expiration' => 'setAssignmentExpiration',
        'assignment_date' => 'setAssignmentDate',
        'username' => 'setUsername',
        'record_code' => 'setRecordCode'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'assignment_expiration' => 'getAssignmentExpiration',
        'assignment_date' => 'getAssignmentDate',
        'username' => 'getUsername',
        'record_code' => 'getRecordCode'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['assignment_expiration'] = isset($data['assignment_expiration']) ? $data['assignment_expiration'] : null;
        $this->container['assignment_date'] = isset($data['assignment_date']) ? $data['assignment_date'] : null;
        $this->container['username'] = isset($data['username']) ? $data['username'] : null;
        $this->container['record_code'] = isset($data['record_code']) ? $data['record_code'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['assignment_expiration'] === null) {
            $invalid_properties[] = "'assignment_expiration' can't be null";
        }
        if ($this->container['username'] === null) {
            $invalid_properties[] = "'username' can't be null";
        }
        if ($this->container['record_code'] === null) {
            $invalid_properties[] = "'record_code' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['assignment_expiration'] === null) {
            return false;
        }
        if ($this->container['username'] === null) {
            return false;
        }
        if ($this->container['record_code'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets assignment_expiration
     * @return string
     */
    public function getAssignmentExpiration()
    {
        return $this->container['assignment_expiration'];
    }

    /**
     * Sets assignment_expiration
     * @param string $assignment_expiration Assignment expiration
     * @return $this
     */
    public function setAssignmentExpiration($assignment_expiration)
    {
        $this->container['assignment_expiration'] = $assignment_expiration;

        return $this;
    }

    /**
     * Gets assignment_date
     * @return string
     */
    public function getAssignmentDate()
    {
        return $this->container['assignment_date'];
    }

    /**
     * Sets assignment_date
     * @param string $assignment_date Assignment date
     * @return $this
     */
    public function setAssignmentDate($assignment_date)
    {
        $this->container['assignment_date'] = $assignment_date;

        return $this;
    }

    /**
     * Gets username
     * @return string
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     * @param string $username Username
     * @return $this
     */
    public function setUsername($username)
    {
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets record_code
     * @return string
     */
    public function getRecordCode()
    {
        return $this->container['record_code'];
    }

    /**
     * Sets record_code
     * @param string $record_code Subscription record code
     * @return $this
     */
    public function setRecordCode($record_code)
    {
        $this->container['record_code'] = $record_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


