<?php
/**
 * ManageUserSessionAdminMenuItems
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * ManageUserSessionAdminMenuItems Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ManageUserSessionAdminMenuItems implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ManageUserSessionAdminMenuItems';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'plugin_menu' => '\Swagger\Client\Model\ManageUserSessionPluginMenu',
        'main_menu' => '\Swagger\Client\Model\ManageUserSessionMainMenu'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'plugin_menu' => 'plugin_menu',
        'main_menu' => 'main_menu'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'plugin_menu' => 'setPluginMenu',
        'main_menu' => 'setMainMenu'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'plugin_menu' => 'getPluginMenu',
        'main_menu' => 'getMainMenu'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['plugin_menu'] = isset($data['plugin_menu']) ? $data['plugin_menu'] : null;
        $this->container['main_menu'] = isset($data['main_menu']) ? $data['main_menu'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['plugin_menu'] === null) {
            $invalid_properties[] = "'plugin_menu' can't be null";
        }
        if ($this->container['main_menu'] === null) {
            $invalid_properties[] = "'main_menu' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['plugin_menu'] === null) {
            return false;
        }
        if ($this->container['main_menu'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets plugin_menu
     * @return \Swagger\Client\Model\ManageUserSessionPluginMenu
     */
    public function getPluginMenu()
    {
        return $this->container['plugin_menu'];
    }

    /**
     * Sets plugin_menu
     * @param \Swagger\Client\Model\ManageUserSessionPluginMenu $plugin_menu Menu items in the Plugin Admin Menu category
     * @return $this
     */
    public function setPluginMenu($plugin_menu)
    {
        $this->container['plugin_menu'] = $plugin_menu;

        return $this;
    }

    /**
     * Gets main_menu
     * @return \Swagger\Client\Model\ManageUserSessionMainMenu
     */
    public function getMainMenu()
    {
        return $this->container['main_menu'];
    }

    /**
     * Sets main_menu
     * @param \Swagger\Client\Model\ManageUserSessionMainMenu $main_menu Menu items in the Main Admin Menu category
     * @return $this
     */
    public function setMainMenu($main_menu)
    {
        $this->container['main_menu'] = $main_menu;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


