<?php
/**
 * LearnCourseImportCoursesItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LearnCourseImportCoursesItemsTest Class Doc Comment
 *
 * @category    Class */
// * @description LearnCourseImportCoursesItems
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LearnCourseImportCoursesItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "LearnCourseImportCoursesItems"
     */
    public function testLearnCourseImportCoursesItems()
    {

    }

    /**
     * Test attribute "course_language"
     */
    public function testPropertyCourseLanguage()
    {

    }

    /**
     * Test attribute "course_description"
     */
    public function testPropertyCourseDescription()
    {

    }

    /**
     * Test attribute "user_enroll_end"
     */
    public function testPropertyUserEnrollEnd()
    {

    }

    /**
     * Test attribute "user_enroll_begin"
     */
    public function testPropertyUserEnrollBegin()
    {

    }

    /**
     * Test attribute "course_validity_begin"
     */
    public function testPropertyCourseValidityBegin()
    {

    }

    /**
     * Test attribute "course_credits"
     */
    public function testPropertyCourseCredits()
    {

    }

    /**
     * Test attribute "course_category"
     */
    public function testPropertyCourseCategory()
    {

    }

    /**
     * Test attribute "course_for_sale"
     */
    public function testPropertyCourseForSale()
    {

    }

    /**
     * Test attribute "course_difficulty"
     */
    public function testPropertyCourseDifficulty()
    {

    }

    /**
     * Test attribute "course_published"
     */
    public function testPropertyCoursePublished()
    {

    }

    /**
     * Test attribute "xxx"
     */
    public function testPropertyXxx()
    {

    }

    /**
     * Test attribute "course_code"
     */
    public function testPropertyCourseCode()
    {

    }

    /**
     * Test attribute "course_validity_end"
     */
    public function testPropertyCourseValidityEnd()
    {

    }

    /**
     * Test attribute "course_type"
     */
    public function testPropertyCourseType()
    {

    }

    /**
     * Test attribute "course_price"
     */
    public function testPropertyCoursePrice()
    {

    }

    /**
     * Test attribute "user_enroll"
     */
    public function testPropertyUserEnroll()
    {

    }

    /**
     * Test attribute "course_cover"
     */
    public function testPropertyCourseCover()
    {

    }

    /**
     * Test attribute "course_name"
     */
    public function testPropertyCourseName()
    {

    }

    /**
     * Test attribute "course_max_subscriptions"
     */
    public function testPropertyCourseMaxSubscriptions()
    {

    }

    /**
     * Test attribute "course_avg_time"
     */
    public function testPropertyCourseAvgTime()
    {

    }

    /**
     * Test attribute "course_status"
     */
    public function testPropertyCourseStatus()
    {

    }

}
