<?php
/**
 * LearnCourseCompactListCanEnterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LearnCourseCompactListCanEnterTest Class Doc Comment
 *
 * @category    Class */
// * @description LearnCourseCompactListCanEnter
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LearnCourseCompactListCanEnterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "LearnCourseCompactListCanEnter"
     */
    public function testLearnCourseCompactListCanEnter()
    {

    }

    /**
     * Test attribute "expiring_in"
     */
    public function testPropertyExpiringIn()
    {

    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {

    }

    /**
     * Test attribute "can"
     */
    public function testPropertyCan()
    {

    }

}
