<?php
/**
 * LearnCatalogueCalendarItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LearnCatalogueCalendarItemsTest Class Doc Comment
 *
 * @category    Class */
// * @description LearnCatalogueCalendarItems
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LearnCatalogueCalendarItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "LearnCatalogueCalendarItems"
     */
    public function testLearnCatalogueCalendarItems()
    {

    }

    /**
     * Test attribute "course_description"
     */
    public function testPropertyCourseDescription()
    {

    }

    /**
     * Test attribute "session_information"
     */
    public function testPropertySessionInformation()
    {

    }

    /**
     * Test attribute "end"
     */
    public function testPropertyEnd()
    {

    }

    /**
     * Test attribute "session_name"
     */
    public function testPropertySessionName()
    {

    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {

    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {

    }

    /**
     * Test attribute "all_day"
     */
    public function testPropertyAllDay()
    {

    }

    /**
     * Test attribute "course_code"
     */
    public function testPropertyCourseCode()
    {

    }

    /**
     * Test attribute "course_category_id"
     */
    public function testPropertyCourseCategoryId()
    {

    }

    /**
     * Test attribute "course_type"
     */
    public function testPropertyCourseType()
    {

    }

    /**
     * Test attribute "course_language"
     */
    public function testPropertyCourseLanguage()
    {

    }

    /**
     * Test attribute "can_enroll"
     */
    public function testPropertyCanEnroll()
    {

    }

    /**
     * Test attribute "course_name"
     */
    public function testPropertyCourseName()
    {

    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {

    }

    /**
     * Test attribute "course_id"
     */
    public function testPropertyCourseId()
    {

    }

}
