<?php
/**
 * ManageSiteBootstrapWsSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ManageSiteBootstrapWsSettingsTest Class Doc Comment
 *
 * @category    Class */
// * @description ManageSiteBootstrapWsSettings
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ManageSiteBootstrapWsSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ManageSiteBootstrapWsSettings"
     */
    public function testManageSiteBootstrapWsSettings()
    {

    }

    /**
     * Test attribute "host"
     */
    public function testPropertyHost()
    {

    }

    /**
     * Test attribute "port"
     */
    public function testPropertyPort()
    {

    }

    /**
     * Test attribute "secure"
     */
    public function testPropertySecure()
    {

    }

}
