<?php
/**
 * ManageUserRegisterSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ManageUserRegisterSchemaTest Class Doc Comment
 *
 * @category    Class */
// * @description ManageUserRegisterSchema
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ManageUserRegisterSchemaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ManageUserRegisterSchema"
     */
    public function testManageUserRegisterSchema()
    {

    }

    /**
     * Test attribute "privacy"
     */
    public function testPropertyPrivacy()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {

    }

    /**
     * Test attribute "lastname"
     */
    public function testPropertyLastname()
    {

    }

    /**
     * Test attribute "user_fields"
     */
    public function testPropertyUserFields()
    {

    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {

    }

    /**
     * Test attribute "userid"
     */
    public function testPropertyUserid()
    {

    }

    /**
     * Test attribute "branch_code"
     */
    public function testPropertyBranchCode()
    {

    }

    /**
     * Test attribute "firstname"
     */
    public function testPropertyFirstname()
    {

    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {

    }

}
