<?php
/**
 * ManageJobViewJobDescriptorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ManageJobViewJobDescriptorTest Class Doc Comment
 *
 * @category    Class */
// * @description ManageJobViewJobDescriptor
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ManageJobViewJobDescriptorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ManageJobViewJobDescriptor"
     */
    public function testManageJobViewJobDescriptor()
    {

    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {

    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {

    }

    /**
     * Test attribute "author_name"
     */
    public function testPropertyAuthorName()
    {

    }

    /**
     * Test attribute "log_file"
     */
    public function testPropertyLogFile()
    {

    }

    /**
     * Test attribute "last_update"
     */
    public function testPropertyLastUpdate()
    {

    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "author_id"
     */
    public function testPropertyAuthorId()
    {

    }

    /**
     * Test attribute "percent"
     */
    public function testPropertyPercent()
    {

    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {

    }

    /**
     * Test attribute "notify"
     */
    public function testPropertyNotify()
    {

    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

}
