<?php
/**
 * SkillRoleListSimulatorDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SkillRoleListSimulatorDataTest Class Doc Comment
 *
 * @category    Class */
// * @description SkillRoleListSimulatorData
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SkillRoleListSimulatorDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SkillRoleListSimulatorData"
     */
    public function testSkillRoleListSimulatorData()
    {

    }

    /**
     * Test attribute "manager"
     */
    public function testPropertyManager()
    {

    }

    /**
     * Test attribute "high_threshold"
     */
    public function testPropertyHighThreshold()
    {

    }

    /**
     * Test attribute "self"
     */
    public function testPropertySelf()
    {

    }

    /**
     * Test attribute "manager_weight"
     */
    public function testPropertyManagerWeight()
    {

    }

    /**
     * Test attribute "peer_weight"
     */
    public function testPropertyPeerWeight()
    {

    }

    /**
     * Test attribute "peer"
     */
    public function testPropertyPeer()
    {

    }

    /**
     * Test attribute "low_threshold"
     */
    public function testPropertyLowThreshold()
    {

    }

    /**
     * Test attribute "self_weight"
     */
    public function testPropertySelfWeight()
    {

    }

}
