<?php
/**
 * SkillEvaluationListUserRequestsItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SkillEvaluationListUserRequestsItemsTest Class Doc Comment
 *
 * @category    Class */
// * @description SkillEvaluationListUserRequestsItems
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SkillEvaluationListUserRequestsItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SkillEvaluationListUserRequestsItems"
     */
    public function testSkillEvaluationListUserRequestsItems()
    {

    }

    /**
     * Test attribute "evaluated_name"
     */
    public function testPropertyEvaluatedName()
    {

    }

    /**
     * Test attribute "request_id"
     */
    public function testPropertyRequestId()
    {

    }

    /**
     * Test attribute "role_id"
     */
    public function testPropertyRoleId()
    {

    }

    /**
     * Test attribute "role_name"
     */
    public function testPropertyRoleName()
    {

    }

    /**
     * Test attribute "evaluated_id"
     */
    public function testPropertyEvaluatedId()
    {

    }

}
