<?php
/**
 * SkillRoleCountRequestsItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SkillRoleCountRequestsItemsTest Class Doc Comment
 *
 * @category    Class */
// * @description SkillRoleCountRequestsItems
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SkillRoleCountRequestsItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SkillRoleCountRequestsItems"
     */
    public function testSkillRoleCountRequestsItems()
    {

    }

    /**
     * Test attribute "users_in_role"
     */
    public function testPropertyUsersInRole()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "eligible_in_role"
     */
    public function testPropertyEligibleInRole()
    {

    }

    /**
     * Test attribute "role_id"
     */
    public function testPropertyRoleId()
    {

    }

    /**
     * Test attribute "in_progress_in_role"
     */
    public function testPropertyInProgressInRole()
    {

    }

    /**
     * Test attribute "completed_in_role"
     */
    public function testPropertyCompletedInRole()
    {

    }

    /**
     * Test attribute "requested_in_role"
     */
    public function testPropertyRequestedInRole()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

}
