<?php
/**
 * LearningObjectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * LearningObjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LearningObjectsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for learningObjectsSkillv1coursesloIdskills
     *
     * Retrieves the list of Skills, that are assigned to given learning object.
     *
     */
    public function testLearningObjectsSkillv1coursesloIdskills()
    {

    }

    /**
     * Test case for learningObjectsSkillv1losloIdprograms
     *
     * Assign a Learning Object to a Program.
     *
     */
    public function testLearningObjectsSkillv1losloIdprograms()
    {

    }

    /**
     * Test case for learningObjectsSkillv1losloIdprograms_0
     *
     * Unassigns a Learning Object from a Program.
     *
     */
    public function testLearningObjectsSkillv1losloIdprograms0()
    {

    }

    /**
     * Test case for learningObjectsSkillv1losloIdskills
     *
     * Assign Skill to a Learning Organization.
     *
     */
    public function testLearningObjectsSkillv1losloIdskills()
    {

    }

    /**
     * Test case for learningObjectsSkillv1losloIdskills_0
     *
     * De-assigns an existing skill(s) from given learning object.
     *
     */
    public function testLearningObjectsSkillv1losloIdskills0()
    {

    }

}
