<?php
/**
 * ThemeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ThemeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ThemeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for themeManagev1theme
     *
     * View all themes.
     *
     */
    public function testThemeManagev1theme()
    {

    }

    /**
     * Test case for themeManagev1themethemeCode
     *
     * View a theme by theme code.
     *
     */
    public function testThemeManagev1themethemeCode()
    {

    }

    /**
     * Test case for themeManagev1themethemeCode_0
     *
     * Update a theme by theme code.
     *
     */
    public function testThemeManagev1themethemeCode0()
    {

    }

    /**
     * Test case for themeManagev1themethemeCode_1
     *
     * Delete a theme.
     *
     */
    public function testThemeManagev1themethemeCode1()
    {

    }

    /**
     * Test case for themeManagev1themethemeCodevariantidMultidomain
     *
     * Update or create a theme variant by theme code and multidomain id.
     *
     */
    public function testThemeManagev1themethemeCodevariantidMultidomain()
    {

    }

}
