<?php
/**
 * UserfieldApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UserfieldApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserfieldApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for userfieldManagev1userFields
     *
     * Retrieves the list of user additional fields, filtered on input parameters.
     *
     */
    public function testUserfieldManagev1userFields()
    {

    }

    /**
     * Test case for userfieldManagev1userFields_0
     *
     * Create user field.
     *
     */
    public function testUserfieldManagev1userFields0()
    {

    }

    /**
     * Test case for userfieldManagev1userFieldsfieldId
     *
     * Get User addtional filds info.
     *
     */
    public function testUserfieldManagev1userFieldsfieldId()
    {

    }

    /**
     * Test case for userfieldManagev1userFieldsfieldId_0
     *
     * Update user fields.
     *
     */
    public function testUserfieldManagev1userFieldsfieldId0()
    {

    }

    /**
     * Test case for userfieldManagev1userFieldsfieldId_1
     *
     * Deletes one user field.
     *
     */
    public function testUserfieldManagev1userFieldsfieldId1()
    {

    }

}
